"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const tasks_1 = require("../handlers/tasks");
const router = (0, express_1.Router)();
router.get('/', tasks_1.getAllTasks);
router.post('/', tasks_1.addTask);
router.get('/:id', tasks_1.getTaskById);
router.put('/:id', tasks_1.updateTask);
router.delete('/:id', tasks_1.deleteTask);
exports.default = router;
